apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - networking/cert-manager/cluster-issuers.yaml
  - networking/cert-manager/test-cert-staging.yaml
  - networking/cert-manager/wildcard-prod.yaml
  - networking/metallb/ippool.yaml
  - networking/traefik-lan/tls-store.yaml
  - networking/traefik-lan/lan-app-routes.yaml
  - networking/traefik-edge/namespace.yaml
  - networking/traefik-edge/tls-store.yaml
  - networking/traefik-edge/firecrawl-edge-auth.yaml
  - networking/traefik-edge/harbor-ingressroute.yaml
  - networking/traefik-edge/legacy-public-routes.yaml
  - networking/traefik-edge/affiliate-public.yaml
  - networking/traefik-edge/static-edge.yaml
  - networking/traefik-edge/wildcard-cert.yaml
  - storage/longhorn/ingressroute.yaml
  - platform/keycloak-next
  - platform/kyverno/policies.yaml
  - platform/vault/auto-unseal.yaml
  - platform/velero/schedules.yaml
  - storage/minio/backup-creds.yaml
