apiVersion: v1
kind: Namespace
metadata:
  name: databases
  labels:
    app.kubernetes.io/part-of: shared-infrastructure
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
