apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ovh-ca
  namespace: infra-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: ovh-ca
    creationPolicy: Owner
  data:
    - secretKey: OVH_ENDPOINT
      remoteRef:
        key: infra/ovh/ca
        property: OVH_ENDPOINT
    - secretKey: OVH_APPLICATION_KEY
      remoteRef:
        key: infra/ovh/ca
        property: OVH_APPLICATION_KEY
    - secretKey: OVH_APPLICATION_SECRET
      remoteRef:
        key: infra/ovh/ca
        property: OVH_APPLICATION_SECRET
    - secretKey: OVH_CONSUMER_KEY
      remoteRef:
        key: infra/ovh/ca
        property: OVH_CONSUMER_KEY
    - secretKey: OVH_SUBSIDIARY
      remoteRef:
        key: infra/ovh/ca
        property: OVH_SUBSIDIARY
    - secretKey: OVH_ACCOUNT_LABEL
      remoteRef:
        key: infra/ovh/ca
        property: OVH_ACCOUNT_LABEL
