apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - database.yaml
  - keycloak.yaml
  - oauth2-proxy.yaml
  - routing.yaml
  - canary.yaml
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: auth-migration
      app.kubernetes.io/managed-by: argocd
