apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: auth-migration
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
