apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-prod-nvme
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: ext4
  dataLocality: disabled
  replicaAutoBalance: best-effort
  diskSelector: nvme
  nodeSelector: ks5-nvme
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-dev
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: ext4
  dataLocality: best-effort
  replicaAutoBalance: ignored
  nodeSelector: home-dev
